# Default values for chisel-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# chisel is the main config
chisel:
# chisel type can be server or client (should always(?) be server here)
  type: "server"
# port is the internal listening port - must match the service port
  port: 34443
# proxy is the hidden target for when a non-chisel request is received
  proxy: "https://remote-rabbit.tf-support.com"
# socks is necessary to decide if there is a need for a socks5 server
  socks: "--socks5"
# path is the path for the waiting tunnel
  path: "/tunnel"
# reverse is whether to enable the reverse tunnel
  reverse: "--reverse"

# replicaCount is the number of necessary replicas
replicaCount: 1

# image sets out the default image
image:
# default repo
  repository: AWS_ACC_NUM.dkr.ecr.us-west-2.amazonaws.com/tf-test-chisel
# default version
  tag: 1.3.1-socks5
# default pullpolicy
  pullPolicy: IfNotPresent

# services sets out the service values
# service is an iteration of a service
# service name should be chisel
# type is typically ClusterIP
# externalPort is the listening svc port
# internalPort is the listening internal pod port - must match chisel.port
# protocol must be TCP
service:
  annotations:
  type: ClusterIP
  ports:
  - name: chisel
    internalPort: 8080
    externalPort: 34443
    protocol: TCP
  - name: kubernetes
    internalPort: 8443
    externalPort: 8443
    protocol: TCP

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  tls: 
  - hosts:
    - remote-rabbit.tf-support.com
    secretName: remote-rabbit-tf-support-tls
  hosts:
    - host: remote-rabbit.tf-support.com
      paths: 
      - path: /tunnel
        backend:
          serviceName: chisel-chisel-helm
          servicePort: 8080
      - path: /*
        backend:
          serviceName: default-http-backend
          servicePort: 80

# not used currently
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# not used currently
nodeSelector: {}

# not used currently
tolerations: []

# not used currently
affinity: {}
