apiVersion: v1
kind: Service
metadata:
  name: {{ include "chisel-helm.fullname" . }}
  labels:
{{ include "chisel-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "chisel-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
{{ range .Values.service.ports }}
  - name: {{ .name | quote }}
    port: {{ .internalPort }}
    targetPort: {{ .externalPort }}
    protocol: {{ .protocol | quote }}
{{- end }}
  