apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chisel-configmap
  labels:
{{ include "chisel-helm.labels" . | indent 4 }}
data:
  {{- with .Values.chisel }}
  type: {{ .type }}
  port: {{ .port }}
  proxy: {{ .proxy }}
  socks: {{ .socks }}
  path: {{ .path }}
  {{- end }}