apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chisel-configmap
  labels:
{{ include "chisel-helm.labels" . | indent 4 }}
data:
  {{- with .Values.chisel }}
  type: {{ .type | quote}}
  port: {{ .port | quote }}
  proxy: {{ .proxy | quote}}
  socks: {{ .socks | quote }}
  path: {{ .path | quote}}
  {{- end }}
  servicename: {{ include "chisel-helm.servicename" . | quote }}