apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chisel-helm.fullname" . }}
  labels:
{{ include "chisel-helm.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chisel-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chisel-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}  
          ports:
          - containerPort: {{ .Values.service.internalPort }}
            protocol: {{ .Values.service.protocol }}
          env:
          - name: TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-chisel-configmap
                key: chisel.type
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-chisel-configmap
                key: chisel.port
          - name: PROXY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-chisel-configmap
                key: chisel.proxy
          - name: SOCKS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-chisel-configmap
                key: chisel.socks
          command: ["/app/chisel", "$(TYPE)", "-v", "-p", "$(PORT)", "--proxy", "$(PROXY)", "$(SOCKS)"]
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.externalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.externalPort }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
